<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);CA2252</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <!-- Support RavenDB 6.x and 7.x (6.0.2 and above) -->
    <PackageReference Include="RavenDB.Client" Version="[6.0.2,8.0.0)" />
    <PackageReference Include="xunit" Version="2.9.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RavenDB.AspNetCore.IdentityCore\RavenDB.AspNetCore.IdentityCore.csproj" />
  </ItemGroup>

</Project>
